# This configuration file defines the mapping of local data into MIABIS CDM fields


# Define the names of each field
field_mappings:

  # Donor/Clinical Information
  PATIENT_ID: ID Patient
  SEX: Sex
  BIRTH_DATE: 
  DONOR_AGE: Donor age
  DIAGNOSIS: Biobanca_ICD code
  AGE_AT_PRIMARY_DIAGNOSIS: Age at Diagnosis #manca
  DATE_DIAGNOSIS : Diagnosis Date #manca

  # Sample Information
  SAMPLE_ID: ID Sample
  SAMPLING_DATE: Sampling date
  MATERIAL_TYPE: Sample Type
  STORAGE_TEMPERATURE: Storage Temperature
  
  
  

# Define the names of each value
value_mappings:
  SEX:
    Male: M
    Female: F
    Undifferentiated: undifferentiated
    Unknown: unknown

  MATERIAL_TYPE:
    Tissue (FFPE): FFPE
    Tissue (Frozen):
      - SNAP FROZEN
      - FROZEN
      - OCT
    Blood: BLOOD
    Faeces: FECIS
    Buffy Coat: BUFFY COAT
    RNA: RNA
    DNA:
    - DNA
    - GDNA
    Saliva: SALIVA
    Urine: URINE
    Immortalized Cell Lines: CELLS
    Other: SN

  STORAGE_TEMPERATURE:
    -60 C to -85 C:
      - "-85"
      - "-80"
    -18 C to -35 C:
      - "-35"
    2 C to 10 C:
      - "10"
    RT: RT
    LN: LN
    Other: Other

