# Configuration

bbmri_structure_definition_url: "https://fhir.bbmri.de/StructureDefinition"
# Server URL
server_url: "http://localhost:8080/fhir"

# Biobank info 
biobank_id: "1547222650173780"
biobank_name: "Biobanca Di Ricerca OPBG"

biobank_alias:
  - "BB-OPBG"

biobank_contact:

  - address:
      use: "work"
      type: "physical"
      country: "IT"
      city: "Rome"
      postalCode: "00146"
      line:
        - "Viale Ferdinando Baldelli Roma"

    telecom:
      - system: "phone"
        value: "+395453534534"
        use: "work"
        rank: 1

      - system: "email"
        value: "pippo.baudo@isnt.it"
        use: "work"
        rank: 1


# Collection info 
collection_id: "1548666951181832"
collection_name: "Rare and Ultra Rare Diseases"

collection_alias:

collection_contact:

  - address:
      use: "work"
      type: "physical"
      country: "IT"
      city: "Rome"
      postalCode: "00146"
      line:
        - "Viale Ferdinando Baldelli Roma"

    telecom:

      - system: "phone"
        value: "+395453534534"
        use: "work"
        rank: 1

      - system: "email"
        value: "pippo.baudo@isnt.it"
        use: "work"
        rank: 1


