# This configuration file defines the mapping of local data into MIABIS CDM fields


# Define the names of each field
field_mappings:

  # Donor/Clinical Information
  PATIENT_ID: ID Patient
  SEX: Sex
  BIRTH_DATE: DOB
  DONOR_AGE: Donor age
  DIAGNOSIS: Biobanca_ICD code
  DIAGNOSIS2: Biobanca_ICD code2
  AGE_AT_PRIMARY_DIAGNOSIS: Age at Diagnosis #manca
  DATE_DIAGNOSIS : Diagnosis date #manca

  # Sample Information
  SAMPLE_ID: ID Sample
  SAMPLING_DATE: Sampling date
  MATERIAL_TYPE: Sample Type
  STORAGE_TEMPERATURE: Storage Temperature
  
  
  

# Define the names of each value
value_mappings:
  SEX:
    Male: M
    Female: F
    Undifferentiated: undifferentiated
    Unknown: unknown

  MATERIAL_TYPE:
    Tissue (FFPE): FFPE
    Tissue (Frozen):
      - SNAP FROZEN
      - FROZEN
      - OCT
    Blood: BLOOD
    Faeces: FECIS
    Buffy Coat: BUFFY COAT
    RNA: RNA
    DNA:
    - DNA
    - GDNA
    Saliva: SALIVA
    Urine: URINE
    Immortalized Cell Lines: CELLS
    Other: SN
    Serum: SERUM
    Plasma: PLASMA
    Liquor: LIQUOR

  STORAGE_TEMPERATURE:
    temperature-60to-85:
      - "-85"
      - "-80"
    temperature-18to-35:
      - "-35"
    temperature2to10:
      - "10"
    temperatureRoom: RT
    temperatureLN: LN
    temperatureOther: Other

