# This configuration file defines the mapping of local data into MIABIS CDM fields
# Please edit the mappings according to your input dataset

# ---------------------------- Field Mapping -------------------------------- #

field_mappings:
  SAMPLE_ID: ID Sample
  PATIENT_ID: ID Patient
  SEX: Sex
  BIRTH_DATE: DOB
  DIAGNOSIS_DONOR_AGE: Age at Diagnosis
  DIAGNOSIS: Biobanca_ICD code
  DIAGNOSIS2: Biobanca_ICD code2
  # DIAGNOSIS_AGE: DIAGNOSIS_AGE
  DIAGNOSIS_DATE: Diagnosis date
  SAMPLING_DATE: Sampling date
  MATERIAL_TYPE: Sample Type
  STORAGE_TEMPERATURE: Storage Temperature

# ---------------------------- Values Mapping -------------------------------- #

value_mappings:
  SEX:
    Male: M
    Female: F
    Undifferentiated: undifferentiated
    Unknown: unknown

  MATERIAL_TYPE:
    Any: any
    Buffy Coat: BUFFY COAT
    cDNA / mRNA: RNA
    Cell lines: CELLS
    DNA: [DNA, GDNA]
    Feces: FECES
    microRNA: RNA
    Nasal swab: NASAL SWAB
    Not available: NA
    Other: LIQUOR
    Pathogen: PATHOGEN
    Peripheral blood cells: PERIPHERAL BLOOD CELLS
    Plasma: PLASMA
    RNA: RNA
    Saliva: SALIVA
    Serum: SERUM
    Throat swab: THROAT SWAB
    Tissue (frozen): [FROZEN, OCT]
    Tissue (paraffin preserved): TissueFFPE
    Tissue (stained sections/slides): STAINED_TISSUE
    Urine: URINE
    Whole Blood: BLOOD

  STORAGE_TEMPERATURE:
    Room temperature: RT
    Liquid Nitrogen: LN
    Other: Other
    -60°C to -80°C: ["-85", "-80"]
    -18°C to -35°C: ["-35"]
    2°C to 10°C: ["10"]
