# This configuration file defines the mapping of local data into MIABIS CDM fields
# Please edit the mappings according to your input dataset
# ---------------------------- Field Mapping -------------------------------- #
field_mappings:
  SAMPLE_ID: Sample_ID
  PATIENT_ID: Patient_ID
  SEX: Gender
  BIRTH_DATE: Donor Birth Date
  DIAGNOSIS_DONOR_AGE: Diagnosis Age Donor
  DIAGNOSIS: Diagnosis ICD-10
  DIAGNOSIS2: /
  # DIAGNOSIS_AGE: DIAGNOSIS_AGE
  DIAGNOSIS_DATE: Date of Diagnosis
  SAMPLING_DATE: Sampling Date
  MATERIAL_TYPE: Sample Type
  STORAGE_TEMPERATURE: Storage Temperature

# ---------------------------- Values Mapping -------------------------------- #

value_mappings:
  SEX:
    Male: M
    Female: F
    Undifferentiated: undifferentiated
    Unknown: unknown

  MATERIAL_TYPE:
    Any: any
    Buffy Coat: Buffy Coat
    cDNA / mRNA: RNA
    Cell lines: [CELLS, CELL]
    DNA: [DNA, GDNA]
    Feces: Feces
    microRNA: RNA
    Nasal swab: NASAL SWAB
    Not available: NA
    Other: Liquor
    Pathogen: Pathogen
    Peripheral blood cells: PERIPHERAL BLOOD CELLS
    Plasma: Plasma
    RNA: RNA
    Saliva: Saliva
    Serum: Serum
    Throat swab: Throat Swab
    Tissue (frozen): [Tissue]
    Tissue (paraffin preserved): [FFPE, Tissue FFPE]
    Tissue (stained sections/slides): Stained Tissue
    Urine: Urine
    Whole Blood: Blood

  STORAGE_TEMPERATURE:
    Room temperature: RT
    Liquid Nitrogen: LN
    Other: Other
    -60°C to -80°C: ["-85", "-80"]
    -18°C to -35°C: ["-20"]
    2°C to 10°C: ["10", "4"]
