# This configuration file defines the mapping of local data into MIABIS CDM fields

# Define the names of each field
field_mappings:
  # Donor/Clinical Information
  PATIENT_ID: PATIENT_ID
  SEX: SEX
  BIRTH_DATE: DOB
  DONOR_AGE: DONOR_AGE
  DIAGNOSIS: ICD-10
  DIAGNOSIS2: null
  DIAGNOSIS_AGE: DIAGNOSIS_AGE
  DATE_DIAGNOSIS: DIAGNOSIS_DATE

  # Sample Information
  SAMPLE_ID: SAMPLE_ID
  SAMPLING_DATE: SAMPLING_DATE
  MATERIAL_TYPE: MATERIAL_TYPE
  STORAGE_TEMPERATURE: STORAGE_TEMPERATURE

# Define the names of each value
value_mappings:
  SEX:
    Male: M
    Female: F
    Undifferentiated: undifferentiated
    Unknown: unknown

  MATERIAL_TYPE:
    Tissue (paraffin preserved): TissueFFPE
    Tissue (frozen): 
      - SNAP FROZEN
      - FROZEN
      - OCT
    Whole Blood: BLOOD
    Faeces: FECES  
    Buffy Coat: BUFFY COAT
    RNA: RNA
    DNA:
      - DNA
      - GDNA
    Saliva: SALIVA
    Urine: URINE
    Cell lines: CELLS
    Other: SN
    Serum: SERUM
    Plasma: PLASMA
    Liquor: LIQUOR

  STORAGE_TEMPERATURE:
    Room temperature: RT 
    Liquid Nitrogen: LN
    Other: Other
    -60°C to -80°C:
      - "-85"
      - "-80"
    -18°C to -35°C:
      - "-35"
    2°C to 10°C:
      - "10"
